In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split


In [2]:
df = pd.read_csv('/Users/jensontmathew/Documents/My_Projects/Myprojects/notebook/data/stud.csv')

In [3]:
df.head()

gender race_ethnicity parental_level_of_education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test_preparation_course  math_score  reading_score  writing_score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [4]:
print("Categories in Gender: ",end=" ")
print(df['gender'].unique())
print("Categories in race_ethnicity: ",end=" ")
print(df['race_ethnicity'].unique())
print("Categories in parental_level_of_education: ",end=" ")
print(df['parental_level_of_education'].unique())
print("Categories in lunch: ",end=" ")
print(df['lunch'].unique())
print("Categories in test_preparation_course: ",end=" ")
print(df['test_preparation_course'].unique())

Categories in Gender:  ['female' 'male']
Categories in race_ethnicity:  ['group B' 'group C' 'group A' 'group D' 'group E']
Categories in parental_level_of_education:  ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
Categories in lunch:  ['standard' 'free/reduced']
Categories in test_preparation_course:  ['none' 'completed']


In [5]:
df

gender race_ethnicity parental_level_of_education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test_preparation_course  math_score  reading_score  writing_score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [6]:
X = df.drop(['math_score'],axis=1)
y = df['math_score']

In [9]:
X

gender race_ethnicity parental_level_of_education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test_preparation_course  reading_score  writing_score  
0                      none             72             74  
1                 completed             90             88  
2                      none             95             93  
3                      none             57             44  
4                      none             78             75  
..                      ...            ...            ...  
995               completed             99             95  
996                    none             55             55  
997               completed             71             65  
998               completed             78             77  
999                    none             86             86  

[1000 rows x 7 columns]

In [11]:
encode = OneHotEncoder(sparse_output=False,drop='first')


In [13]:
gender_encoded = encode.fit_transform(X[['gender']],)

In [21]:
# c=pd.DataFrame(gender_encoded,columns='gender')

In [24]:
c=pd.get_dummies(X)

In [25]:
one_hot_encoded_df = pd.get_dummies(df, columns=['Category'])

reading_score  writing_score  gender_female  gender_male  \
0               72             74           True        False   
1               90             88           True        False   
2               95             93           True        False   
3               57             44          False         True   
4               78             75          False         True   
..             ...            ...            ...          ...   
995             99             95           True        False   
996             55             55          False         True   
997             71             65           True        False   
998             78             77           True        False   
999             86             86           True        False   

     race_ethnicity_group A  race_ethnicity_group B  race_ethnicity_group C  \
0                     False                    True                   False   
1                     False                   False                    True   
2                     False                    True                   False   
3                      True                   False                   False   
4                     False                   False                    True   
..                      ...                     ...                     ...   
995                   False                   False                   False   
996                   False                   False                    True   
997                   False                   False                    True   
998                   False                   False                   False   
999                   False                   False                   False   

     race_ethnicity_group D  race_ethnicity_group E  \
0                     False                   False   
1                     False                   False   
2                     False                   False   
3                     False                   False   
4                     False                   False   
..                      ...                     ...   
995                   False                    True   
996                   False                   False   
997                   False                   False   
998                    True                   False   
999                    True                   False   

     parental_level_of_education_associate's degree  \
0                                             False   
1                                             False   
2                                             False   
3                                              True   
4                                             False   
..                                              ...   
995                                           False   
996                                           False   
997                                           False   
998                                           False   
999                                           False   

     parental_level_of_education_bachelor's degree  \
0                                             True   
1                                            False   
2                                            False   
3                                            False   
4                                            False   
..                                             ...   
995                                          False   
996                                          False   
997                                          False   
998                                          False   
999                                          False   

     parental_level_of_education_high school  \
0                                      False   
1                                      False   
2                                      False   
3                                      False   
4                                      False   
..              

In [30]:
encode = OneHotEncoder(sparse_output=False,drop='first')

In [31]:
gender_encoded = encode.fit_transform(df[['gender']])
race_encoded = encode.fit_transform(df[['race_ethnicity']])
parental_encoded = encode.fit_transform(df[['parental_level_of_education']])
lunch_encoded = encode.fit_transform(df[['lunch']])
test_encoded = encode.fit_transform(df[['test_preparation_course']])

In [33]:
data = {
    'gender_encoded': gender_encoded.squeeze(),
    'race_encoded': race_encoded.squeeze(),
    'parental_encoded': parental_encoded.squeeze(),
    'lunch_encoded': lunch_encoded.squeeze(),
    'test_encoded': test_encoded.squeeze()
}

In [35]:
df.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='object')

In [37]:
gender_dataframe = pd.DataFrame(data,columns=['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'])

In [41]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample data
data = np.array(['A', 'B', 'A', 'C', 'B', 'A']).reshape(-1, 1)

# Initialize the OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the data
one_hot_encoded = one_hot_encoder.fit_transform(data)

print("One-Hot Encoded Data:\n", one_hot_encoded)


One-Hot Encoded Data:
 [[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [42]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Sample data (assuming it's in a CSV format, you can replace this with your DataFrame)
data = {
    'gender': ['female', 'female', 'female', 'male', 'male'],
    'race_ethnicity': ['group B', 'group C', 'group B', 'group A', 'group C'],
    'parental_level_of_education': ["bachelor's degree", 'some college', "master's degree", "associate's degree", 'some college'],
    'lunch': ['standard', 'standard', 'standard', 'free/reduced', 'standard'],
    'test_preparation_course': ['none', 'completed', 'none', 'none', 'none'],
    'reading_score': [72, 90, 95, 57, 78],
    'writing_score': [74, 88, 93, 44, 75]
}

df = pd.DataFrame(data)

# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse=False, drop='first')  # Use drop='first' to avoid the dummy variable trap

# Select categorical columns
categorical_cols = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

# Fit and transform the encoder on the categorical columns
one_hot_encoded = encoder.fit_transform(df[categorical_cols])

# Create a DataFrame with the encoded features
encoded_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_cols))

# Concatenate the encoded features with the original DataFrame (excluding original categorical columns)
df_encoded = pd.concat([df.drop(categorical_cols, axis=1), encoded_df], axis=1)

print(df_encoded.head())


   reading_score  writing_score  gender_male  race_ethnicity_group B  \
0             72             74          0.0                     1.0   
1             90             88          0.0                     0.0   
2             95             93          0.0                     1.0   
3             57             44          1.0                     0.0   
4             78             75          1.0                     0.0   

   race_ethnicity_group C  parental_level_of_education_bachelor's degree  \
0                     0.0                                            1.0   
1                     1.0                                            0.0   
2                     0.0                                            0.0   
3                     0.0                                            0.0   
4                     1.0                                            0.0   

   parental_level_of_education_master's degree  \
0                                          0.0   
1         

/Users/jensontmathew/opt/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [46]:
print(df_encoded.shape)


(5, 10)


In [47]:
df_encoded = pd.get_dummies(df, columns=['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course'], drop_first=True)


In [48]:
df_encoded

reading_score  writing_score  gender_male  race_ethnicity_group B  \
0             72             74        False                    True   
1             90             88        False                   False   
2             95             93        False                    True   
3             57             44         True                   False   
4             78             75         True                   False   

   race_ethnicity_group C  parental_level_of_education_bachelor's degree  \
0                   False                                           True   
1                    True                                          False   
2                   False                                          False   
3                   False                                          False   
4                    True                                          False   

   parental_level_of_education_master's degree  \
0                                        False   
1                                        False   
2                                         True   
3                                        False   
4                                        False   

   parental_level_of_education_some college  lunch_standard  \
0                                     False            True   
1                                      True            True   
2                                     False            True   
3                                     False           False   
4                                      True            True   

   test_preparation_course_none  
0                          True  
1                         False  
2                          True  
3                          True  
4                          True

In [49]:
df_encoded = pd.get_dummies(df, columns=['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course'], drop_first=True)


In [50]:
df_encoded

reading_score  writing_score  gender_male  race_ethnicity_group B  \
0             72             74        False                    True   
1             90             88        False                   False   
2             95             93        False                    True   
3             57             44         True                   False   
4             78             75         True                   False   

   race_ethnicity_group C  parental_level_of_education_bachelor's degree  \
0                   False                                           True   
1                    True                                          False   
2                   False                                          False   
3                   False                                          False   
4                    True                                          False   

   parental_level_of_education_master's degree  \
0                                        False   
1                                        False   
2                                         True   
3                                        False   
4                                        False   

   parental_level_of_education_some college  lunch_standard  \
0                                     False            True   
1                                      True            True   
2                                     False            True   
3                                     False           False   
4                                      True            True   

   test_preparation_course_none  
0                          True  
1                         False  
2                          True  
3                          True  
4                          True

In [51]:
df = pd.read_csv('/Users/jensontmathew/Documents/My_Projects/Myprojects/notebook/data/stud.csv')

In [52]:
df_encoded = pd.get_dummies(df, columns=['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course'], drop_first=True)


In [53]:
df_encoded

math_score  reading_score  writing_score  gender_male  \
0            72             72             74        False   
1            69             90             88        False   
2            90             95             93        False   
3            47             57             44         True   
4            76             78             75         True   
..          ...            ...            ...          ...   
995          88             99             95        False   
996          62             55             55         True   
997          59             71             65        False   
998          68             78             77        False   
999          77             86             86        False   

     race_ethnicity_group B  race_ethnicity_group C  race_ethnicity_group D  \
0                      True                   False                   False   
1                     False                    True                   False   
2                      True                   False                   False   
3                     False                   False                   False   
4                     False                    True                   False   
..                      ...                     ...                     ...   
995                   False                   False                   False   
996                   False                    True                   False   
997                   False                    True                   False   
998                   False                   False                    True   
999                   False                   False                    True   

     race_ethnicity_group E  parental_level_of_education_bachelor's degree  \
0                     False                                           True   
1                     False                                          False   
2                     False                                          False   
3                     False                                          False   
4                     False                                          False   
..                      ...                                            ...   
995                    True                                          False   
996                   False                                          False   
997                   False                                          False   
998                   False                                          False   
999                   False                                          False   

     parental_level_of_education_high school  \
0                                      False   
1                                      False   
2                                      False   
3                                      False   
4                                      False   
..                                       ...   
995                                    False   
996                                     True   
997                                     True   
998                                    False   
999                                    False   

     parental_level_of_education_master's degree  \
0                                          False   
1                                          False   
2                                           True   
3                                          False   
4                                          False   
..                                           ...   
995                                         True   
996                                        False   
997                                        False   
998                                        False   
999                                        False   

     parental_level_of_education_some college  \
0                                       False   
1                                        True   
2                        